---
- name: Prepare website
  hosts: local
  connection: local
  tasks:
    - name: LOCAL - Clean directory
      file:
        path: "{{ playbook_dir }}/website"
        state: absent

    - name: LOCAL - Clone repository
      git:
        clone: yes
        repo: git@github.com:event-sonar/website.git
        dest: "{{ playbook_dir }}/website"
        key_file: ~/.ssh/id_rsa
        accept_hostkey: yes

    - name: LOCAL - Composer install
      command: composer install --no-interaction --no-progress --no-scripts --optimize-autoloader --no-dev
      args:
        chdir: "{{ playbook_dir }}/website"

    - name: LOCAL - Npm install
      command: npm install
      args:
        chdir: "{{ playbook_dir }}/website"

    - name: LOCAL - Npm build app
      command: npm run prod
      args:
        chdir: "{{ playbook_dir }}/website"

    - name: LOCAL - Remove .git
      file:
        path: "{{ playbook_dir }}/website/.git"
        state: absent

    - name: LOCAL - Remove .gitignore
      file:
        path: "{{ playbook_dir }}/website/.gitignore"
        state: absent

    - name: LOCAL - Remove .env
      file:
        path: "{{ playbook_dir }}/website/.env"
        state: absent

    - name: LOCAL - Remove assets
      file:
        path: "{{ playbook_dir }}/website/assets"
        state: absent

    - name: LOCAL - Remove node_modules
      file:
        path: "{{ playbook_dir }}/website/node_modules"
        state: absent
